config/routes.rb
Rails.application.routes.draw do
  resources :memes do
    resources :reviews
  end

  resources :admins, only: [:index, :destroy] do
    get '/make_admin', to: 'admins#make_admin'
    get '/remove_admin', to: 'admins#remove_admin'
  end

  namespace :api do
    namespace :v1 do
      resources :memes, only: [:show] do
        resources :reviews, only: [:index, :update, :destroy]
      end
    end
  end

  root 'memes#index'

  devise_for :users
end

app/models/meme.rb
class Meme < ApplicationRecord
  belongs_to :contributor, class_name: "User"
  has_many :reviews

  has_many :reviews

  validates :name, presence: true
  validates :name, uniqueness: true
  validates :image_url, presence: true

  validates :contributor_id, presence: true

  def self.search(search)
    where("name ILIKE ? ", "%#{search}%")
  end
end

app/controllers/memes_controller.rb
class MemesController < ApplicationController
  before_action :authenticate_user!, only: [:create]
  before_action :authorize_user, only: [:create]

  def index
    if params[:search]
      @memes = Meme.search(params[:search])
    else
      @memes = Meme.all
    end
  end

  def new
    if current_user.nil?
      flash[:errors] = "Please sign in first."
      redirect_to memes_path
    end
    @meme = Meme.new
  end

  def create
    if current_user.nil?
      flash[:errors] = "Please sign in first."
      redirect_to memes_path
    else
      @meme = Meme.new(meme_params)
      @meme.contributor = current_user
      if @meme.save
        flash[:success] = 'Meme added successfully'
        redirect_to meme_path(@meme)
      else
        flash[:errors] = @meme.errors.full_messages.join(', ')
        render :new
      end
    end
  end

  def show
    @meme = Meme.find(params[:id])
    @review = Review.new
    @reviews = @meme.reviews
    @current_user_review = false
    if !@reviews.find_by_user_id(current_user).nil?
      @current_user_review = true
    end
    @current_user_id = 0
    if !current_user.nil?
      @current_user_id = current_user.id
    end
  end

  def destroy
    @meme = Meme.find(params[:id])
    @meme.destroy
    flash[:success] = "Meme deleted successfully"
    redirect_to memes_path
  end

  def edit
    @meme = Meme.find(params[:id])
  end

  def update
    @meme = Meme.find(params[:id])
    @new_meme = @meme.update_attributes(meme_params)
    if @meme.save
      flash[:success] = 'Meme updated successfully'
      redirect_to meme_path(@meme)
    else
      flash[:errors] = @meme.errors.full_messages.join(', ')
      render :edit
    end
  end

  private

  def meme_params
    params.require(:meme).permit(:name, :image_url, :description)
  end

  def authorize_user
    if !current_user.admin?
      raise ActionController::RoutingError.new("Need Admin Credentials to add meme")
    end
  end
end

app/views/memes/edit.html.erb
<div class= "row">
  <h1> Update a Meme </h1>

  <%= form_for(@meme) do |f| %>
    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :description %>
      <%= f.text_area :description%>
    </div>
    <div class="field">
      <%= f.label :image_url, "Link to Image"%>
      <%= f.text_area :image_url%>
    </div>
    <div class="actions">
      <%= f.submit "Update Meme", class: "button"%>
    </div>
  <% end %>
  <p><%= link_to "Back", root_path %></p>
</div>

app/views/memes/index.html.erb
<div class="row">
  <h1 class="meme-search">Memes</h1>
  <%= form_tag(memes_path, :method => "get", id: "search-form") do %>
    <div class="input-group">
      <%= text_field_tag :search, params[:search], placeholder: "Search Memes", class: "input-group-field" %>
      <div class="input-group-button">
        <%= submit_tag "Search", :name => nil, class: "search-button button" %>
      </div>
    </div>
  <% end %>
</div>

<% i = 0 %>
<% while i < @memes.length do %>
  <div class="row text-center">
    <div class="small-12 large-4 columns">
      <h3><%= link_to @memes[i].name, meme_path(@memes[i].id) %></h3>
      <%= link_to image_tag(@memes[i].image_url, :alt => @memes[i].name, :class => "thumbnail"), meme_path(@memes[i].id) %>
      <% if user_signed_in? && current_user.admin? %>
        <%= link_to 'Delete Meme', @memes[i], method: :delete, data: {confirm: "Are you sure?"}, class: "button" %>
      <% end %>
    </div>
    <div class="small-12 large-4 columns">
      <% if @memes[i+1] %>
        <h3><%= link_to @memes[i+1].name, meme_path(@memes[i+1].id) %></h3>
        <%= link_to image_tag(@memes[i+1].image_url, :alt => @memes[i+1].name, :class => "thumbnail"), meme_path(@memes[i+1].id) %>
        <% if user_signed_in? && current_user.admin? %>
          <%= link_to 'Delete Meme', @memes[i+1], method: :delete, data: {confirm: "Are you sure?"}, class: "button" %>
        <% end %>
      <% end %>
    </div>
    <div class="small-12 large-4 columns">
      <% if @memes[i+2] %>
        <h3><%= link_to @memes[i+2].name, meme_path(@memes[i+2].id) %></h3>
        <%= link_to image_tag(@memes[i+2].image_url, :alt => @memes[i+2].name, :class => "thumbnail"), meme_path(@memes[i+2].id) %>
        <% if user_signed_in? && current_user.admin? %>
          <%= link_to 'Delete Meme', @memes[i+1], method: :delete, data: {confirm: "Are you sure?"}, class: "button" %>
        <% end %>
      <% end %>
    </div>
  </div>
  <% i += 3 %>
<% end %>

<div class="row">
  <% if user_signed_in? && current_user.admin? %>
    <h5><%= link_to 'See Users', admins_path %></h5>
  <% end %>
</div>

<div class="row">
  <h5><%= link_to 'Add New Meme!', new_meme_path %></h5>
</div>

app/views/memes/new.html.erb
<div class= "row">
  <h1> Submit a Meme </h1>

  <%= form_for(@meme) do |f| %>
    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :description %>
      <%= f.text_area :description%>
    </div>
    <div class="field">
      <%= f.label :image_url, "Link to Image"%>
      <%= f.text_area :image_url%>
    </div>
    <div class="actions">
      <%= f.submit "Add Meme", class: "button"%>
    </div>
  <% end %>
  <p><%= link_to "Back", root_path %></p>
</div>

app/views/memes/show.html.erb
<div class="row text-center">
  <h1><%= @meme.name %></h1>
  <p><strong>Contributor:</strong> <%= @meme.contributor.username %></p>
</div>
<div class="row text-center">
  <img src=<%= @meme.image_url %> alt=<%= @meme.name %> class="meme-image thumbnail">
</div>
<div class="row text-center">
  <p><%= @meme.description %></p>
</div>
<div class="row">
  <h5><%= link_to 'Update a Meme', edit_meme_path  %></h5>
  <h5><%= link_to 'Delete Meme', @meme, method: :delete, data: {confirm: "Are you sure?"} %></h5>
</div>

<div class="row">
  <h3>Reviews:</h3>
</div>
<div id="app"></div>

<% unless @review.errors.empty? %>
  <div>
    <%= @meme.errors.full_messages.to_sentence %>
  </div>
<% end %>

<div class="row">
  <% if !@current_user_review %>
    <h5 class="text-center">Review this Meme</h5>
    <%= form_for [@meme, @review] do |f| %>
    <div class="small-2 columns">
      <div class="input-group">
        <%= f.label :rating, class: "input-group-label" %>
        <%= f.text_field :rating, class: "input-group-field" %>
      </div>
    </div>
    <div class="small-10 columns">
      <div class="input-group">
        <%= f.label :body, class: "input-group-label" %>
        <%= f.text_field :body, class: "input-group-field" %>
      </div>
    </div>
    <div class="actions">
      <%= f.submit "Add Review", class: "button"%>
    </div>
    <% end %>
  <% end %>
  <p><%= link_to "Back", memes_path %></p>
</div>