config/routes.rb
Rails.application.routes.draw do
  resources :memes do
    resources :reviews
  end

  resources :admins, only: [:index, :destroy] do
    get '/make_admin', to: 'admins#make_admin'
    get '/remove_admin', to: 'admins#remove_admin'
  end

  namespace :api do
    namespace :v1 do
      resources :memes, only: [:show] do
        resources :reviews, only: [:index, :update, :destroy]
      end
    end
  end

  root 'memes#index'

  devise_for :users
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Take On Meme" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <% flash.each do |type, message| %>
      <div class="<%= "flash #{type}" %>">
         <%= message %>
      </div>
    <% end %>

    <div class="top-bar">
      <div class="top-bar-left">
        <ul class="menu">
          <li class="menu-text"><%= link_to "Take On Meme", root_path %></li>
          <li><%= link_to "Memes", memes_path %></li>
          <li><a href="#">Categories</a></li>
        </ul>
      </div>
      <div class="top-bar-right">
        <ul class="menu">
          <% if signed_in? %>
            <li class="username"><%= current_user.username %></li>
            <li><img class="avatar" src="<%= current_user.avatar_url %>" alt="user-avatar"></li>
            <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
            <li><%= link_to "Sign out", destroy_user_session_path, data: { method: 'delete' } %></li>
          <% else %>
            <li><%= link_to "Sign in", new_user_session_path %></li>
            <li><%= link_to "Join", new_user_registration_path %></li>
          <% end %>
        </ul>
      </div>
    </div>

    <%= yield %>

  </body>
</html>